version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=your_db_user
      - DB_PASS=your_db_password
      - DB_NAME=your_db_name
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_db_name
      - MYSQL_USER=your_db_user
      - MYSQL_PASSWORD=your_db_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

