services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./video:/app/video
      - ./audio:/app/audio
      - ./texts:/app/texts
      - wwebjs_auth:/app/.wwebjs_auth
      - wwebjs_cache:/app/.wwebjs_cache
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "--wait-timeout=28800"

volumes:
  wwebjs_auth:
  wwebjs_cache:
  mariadb_data:

